[package]
edition = "2021"
name = "beff-core"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
env_logger = "0.10.0"
jsdoc = "0.108.0"
log = "0.4.20"
serde = "1.0.188"
serde_json = "1.0.105"
swc_atoms = "0.5.9"
swc_common = "0.32.0"
swc_ecma_ast = "0.109.0"
swc_ecma_codegen = "0.144.0"
swc_ecma_parser = "0.139.0"
swc_ecma_transforms_base = "0.132.1"
swc_ecma_visit = "0.95.0"
swc_node_comments = "0.19.0"
