[package]
edition = "2021"
name = "swc-bff"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
ariadne = "0.3.0"
assert_cmd = "2.0.12"
clap = {version = "4.4.1", features = ["derive"]}
env_logger = "0.10.0"
is-macro = "0.3.0"
jsdoc = "0.108.0"
log = "0.4.20"
notify = {version = "6.1.1", features = ["serde"]}
notify-debouncer-mini = "0.4.1"
serde = {version = "1.0.188", features = ["derive"]}
serde_json = "1.0.105"
swc_atoms = "0.5.9"
swc_bundler = "0.219.0"
swc_common = "0.32.0"
swc_core = "0.82.1"
swc_ecma_ast = "0.109.0"
swc_ecma_codegen = "0.144.0"
swc_ecma_loader = {version = "0.44.2", features = ["node", "cache"]}
swc_ecma_minifier = "0.186.0"
swc_ecma_parser = "0.139.0"
swc_ecma_transforms_base = "0.132.0"
swc_ecma_transforms_module = "0.175.0"
swc_ecma_utils = "0.122.0"
swc_ecma_visit = "0.95.0"
swc_error_reporters = "0.16.0"
swc_node_comments = "0.19.0"
