name: Tests
on: [push]
jobs:
  tests:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      # Setup .npmrc file to publish to npm
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          registry-url: "https://registry.npmjs.org"
      - name: Tests
        run: |
          pnpm install
          pnpm prettier:check
          pnpm wasm:dev
          curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
          DEBUG=true pnpm all
          git diff-index --cached --quiet HEAD || (echo "Error: There are changed files" && exit 1)
